### ISSUE TITLE
Add `variant` prop for DataTable

### ISSUE THREAD

**Issue by aswinshenoy** [traboda/chaya#35]
Add support for a new prop type for DataTable - `variant` of type ENUM string - 
- `simple`(default)
- `grid`
- `striped-rows`
- `striped-columns`

## simple

![image](https://user-images.githubusercontent.com/21276922/214773776-3b4e5da2-0af9-4dd5-b34d-8926413cca96.png)

(pretty much, just like how ours looks today)

## grid 

![image](https://user-images.githubusercontent.com/21276922/214774372-e10cf0a2-8738-4432-a235-66f3d18dd0ff.png)

https://ant.design/components/table#components-table-demo-edit-cell

## striped-columns

![image](https://user-images.githubusercontent.com/21276922/214774032-6b99c9c0-1e42-4744-bc84-856e25c94346.png)

- https://flowbite.com/docs/components/tables/#striped-columns

## striped-rows

![image](https://user-images.githubusercontent.com/21276922/214774054-1fdc5dfc-ceb5-4281-87fd-55ac38e67c02.png)

- https://flowbite.com/docs/components/tables/#striped-rows

**Comment by Advaith3600** [comment]
Closed by #92
