### ISSUE TITLE
Table not filling available width

### ISSUE THREAD

**Issue by aswinshenoy** [traboda/chaya#7]
Table should fill to available width. This can be done through -> some property (atleast 1) which is not explicitly set a width (in the below example that could be the name column/property) - it can take the remaining width in the available width. This should however not cause the table to overflow beyond 100% unnecessarily..

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/21276922/187509812-3082108f-13d7-439b-97c4-0bb7c20961f8.png">

**Comment by Advaith3600** [comment]
Fixed while upgrading to v1
