### ISSUE TITLE
Add badge prop support for TabSwitcher titles

### ISSUE THREAD

**Issue by aswinshenoy** [traboda/chaya#8]
Tab titles should have support to have badges (which could be some numbers to show stats, or perhaps tags like `new` etc.)

the prop `badge` should take props of `Badge` component we already have or otherwise an instance of Badge component alone.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/21276922/187523845-38f5c555-428b-4a7b-b1a1-bb494eda6be4.png">

**Comment by Advaith3600** [comment]
This feature was added in v0 itself
