### ISSUE TITLE
Bug:  Default selected value in SelectorButton is not sent onSubmit

### ISSUE THREAD

**Issue by aswinshenoy** [traboda/chaya#87]
**Describe the bug**
The `onSubmit` callback does not send any value if no selection was explicitly made by the user, while the user maybe seeing a option to be already selected (so, now he wants that option, he might hit submit, and this value is never recieved at the consumer app).

**Expected behavior**
Selector button should set its internal `value` state to a default option from options (as it will get previewed by `SimpleSelector` downstream) or explicitly make the user select an option and by default not have any option selected.

**Screenshots**

![image](https://user-images.githubusercontent.com/21276922/224549243-8db16f6a-5e2f-4dbc-ab27-a63314f83bdb.png)

after explicit selection,

![image](https://user-images.githubusercontent.com/21276922/224549262-0c9c9636-b1ac-49a5-b173-5ebf1b71ee4b.png)

**Comment by Advaith3600** [comment]
Fixed in b351eb699e5b2d3d5849761fb4633d16236107c1
