### ISSUE TITLE
Add `Spinner` Component

### ISSUE THREAD

**Issue by aswinshenoy** [traboda/chaya#88]
## Props
```
id: string
size: 'sm' | 'md' | 'lg'
color: 'primary' | 'success' | 'warning' | 'danger' | 'contrast' | 'shade'
```

## Inspirations
[GitHub Primer Spinner](https://primer.style/react/Spinner)

**Comment by Advaith3600** [comment]
Fixes [a99ee3e](https://github.com/traboda/chaya/commit/a99ee3e4868b6b101dbb9d8f1a3ce95efbebc5aa)
